version: "3.1"
services:
  vote-db-postgresql:
    image: postgres:16.0
    container_name: platform
    environment:
      - POSTGRES_DB=vote-platform
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Godalzinh0
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: