spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vote-platform
    username: root
    password: Godalzinh0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true